CREATE TABLE TBL_FORNECEDOR(
	FCODIGO SERIAL NOT NULL,
	FNOME VARCHAR(50) NOT NULL,
	FSTATUS VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
	FNUMERO VARCHAR(50) NOT NULL,
	PRIMARY KEY (FCODIGO)
);

CREATE TABLE TBL_PECA(
	PCODIGO SERIAL NOT NULL,
	PNOME VARCHAR(30) NOT NULL,
	PCOR VARCHAR(30) NOT NULL,
	PESO DECIMAL(7,2) NOT NULL,
	PCIDADE VARCHAR(30) NOT NULL
	PRIMARY KEY(PCODIGO)
);

CREATE TABLE TBL_INSTITUICAO(
	ICODIGO SERIAL NOT NULL,
	INOME VARCHAR(30) NOT NULL,
	PRIMARY KEY (ICODIGO)
);

CREATE TABLE TBL_PROJETO(
	PRCODIGO SERIAL NOT NULL,
	PRNOME VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ICODIGO INT NOT NULL,
	PRIMARY KEY (PRCODIGO),
	FOREIGN KEY (ICODIGO) REFERENCES TBL_INSTITUICAO(ICODIGO)
);

CREATE TABLE TBL_FORNECIMENTO(
	FCODIGO SERIAL NOT NULL,
	PCODIGO SERIAL NOT NULL,
	PRCODIGO SERIAL NOT NULL,
	QTDE INT NOT NULL,
	PRIMARY KEY (FCODIGO, PCODIGO, PRCODIGO),
	FOREIGN KEY (FCODIGO) REFERENCES TBL_FORNECEDOR(FCODIGO),
	FOREIGN KEY (PCODIGO) REFERENCES TBL_PECA(PCODIGO),
	FOREIGN KEY (PRCODIGO) REFERENCES TBL_PROJETO(PRCODIGO)
);

CREATE INDEX IDX_ICODIGO ON TBL_PROJETO(ICODIGO);
CREATE INDEX IDX_FCODIGO ON TBL_FORNECIMENTO(FCODIGO);
CREATE INDEX IDX_PCODIGO ON TBL_FORNECIMENTO(PCODIGO);
CREATE INDEX IDC_PRCODIGO ON TBL_FORNECIMENTO(PRCODIGO);


SELECT * FROM tbl_fornecedor;

CREATE TABLE TBL_CIDADE(
	CCODE SERIAL NOT NULL,
	CNOME VARCHAR(50) NOT NULL,
	CESTADO VARCHAR(50) NOT NULL,
	PRIMARY KEY (CCODE)
)

INSERT INTO tbl_fornecedor(
VALUES(default,'Kalunga',default,'1930234066'),
	(default,'LLC Logistica','inativo','1130245578'),
	(default,'Velho Barreiro',default,'1930324068'),
	(default,'Hyundai',default,'1930224545')
)

INSERT INTO tbl_fornecedor(
VALUES(default,'Kalunga','','1930234066')
	)


INSERT INTO tbl_cidade(
VALUES(18,'',null),
	(19,'Rio Claro', 'SP'),
	(20,'Piracicaba','SO')
)

INSERT INTO TBL_PECA(
VALUES(DEFAULT,'Processador','Padrao',300,13),
	(default,'Lona','Azul',12,11),
	(default,'Cachaça','Transparante',11,14),
	(default,'Hyundai Creta','100',10000,15)
)

INSERT INTO TBL_PROJETO(
VALUES(DEFAULT,'Eletronicos','Limeira',11),
	(default,'Mecanicos','Piracicaba',13),
	(default,'Escolas','Rio Claro',12)
)

SELECT * from tbl_cidade

delete from tbl_fornecedor
where fstatus = ''

truncate table tbl_cidade cascade