CREATE TABLE cadfun(
  CODFUN SERIAL NOT NULL PRIMARY KEY,
  NOME VARCHAR(40) NOT NULL,
  DEPTO CHAR(2),
  FUNCAO CHAR(20),
  SALARIO NUMERIC(10,2)
);

INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'CARLOS ALBERTO','3','VENDEDOR',1530.00);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'MARCOS HENRIQUE','2','GERENTE',1985.75);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'APARECIDA SILVA','3','SECRETARIA',1200.50);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'SOLANGE PACHECO','5','SUPERVISORA',1599.51);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'MARCELO SOUZA','3','ANALISTA',2250.11);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO)
VALUES(default,'CELTA NASCIMENTO','2','SECRETARIA',1999.50);
INSERT INTO cadfun VALUES (default,'WILSON DE MACEDO','3','PROGRAMADOR', 1050.00);
INSERT INTO cadfun VALUES (default,'AUGUSTO SOUZA','3','PROGRAMADOR',1050.00);
INSERT INTO cadfun VALUES (default,'CARLOS BASTOS','5','VENDEDOR',1530.00);
INSERT INTO cadfun VALUES (default,'PEDRO SILVA','3','SUPERVISOR',1599.51);
INSERT INTO cadfun VALUES (default,'ANA BASTOS','5','VENDEDORA',1530.00);
INSERT INTO cadfun VALUES (default,'PAULO DA SILVA','2','VENDEDOR',1530.00);

select * from cadfun;

SELECT NOME,FUNCAO from cadfun;

--CONDICIONAIS
SELECT NOME,SALARIO FROM cadfun
WHERE CODFUN=1;

SELECT NOME,SALARIO FROM cadfun
WHERE FUNCAO = 'PROGRAMADOR';

SELECT NOME,SALARIO FROM cadfun
WHERE SALARIO  < 3500 OR DEPTO = '5';

SELECT SALARIO FROM cadfun;
SELECT DISTINCT SALARIO FROM cadfun;

SELECT DEPTO FROM cadfun;
SELECT DISTINCT DEPTO FROM cadfun;

SELECT NOME, SALARIO FROM cadfun
order BY NOME ASC;

SELECT NOME , SALARIO FROM cadfun
ORDER BY NOME DESC;

SELECT NOME, SALARIO FROM cadfun
ORDER BY SALARIO DESC;

SELECT * FROM cadfun
ORDER BY NOME;

SELECT NOME, FUNCAO FROM cadfun
ORDER BY FUNCAO, NOME DESC;

SELECT NOME FROM cadfun
WHERE CODFUN = 2
ORDER BY NOME;

SELECT NOME, SALARIO FROM cadfun
ORDER BY NOME
limit 3;

SELECT NOME, SALARIO FROM cadfun
ORDER BY NOME
limit 3 offset 3;