CREATE TABLE cadfun(
  CODFUN SERIAL NOT NULL PRIMARY KEY,
  NOME VARCHAR(40) NOT NULL,
  DEPTO CHAR(2),
  FUNCAO CHAR(20),
  SALARIO NUMERIC(10,2),
  FILHOS NUMERIC(10,2)
);

INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'CARLOS ALBERTO','3','VENDEDOR',1530.00,3);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'MARCOS HENRIQUE','2','GERENTE',1985.75,3);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'APARECIDA SILVA','3','SECRETARIA',1200.50,2);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'SOLANGE PACHECO','5','SUPERVISORA',1599.51,4);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'MARCELO SOUZA','3','ANALISTA',2250.11,1);
INSERT INTO cadfun (CODFUN,NOME,DEPTO,FUNCAO,SALARIO,FILHOS)
VALUES(default,'CELTA NASCIMENTO','2','SECRETARIA',1999.50,5);
INSERT INTO cadfun VALUES (default,'WILSON DE MACEDO','3','PROGRAMADOR', 1050.00,4);
INSERT INTO cadfun VALUES (default,'AUGUSTO SOUZA','3','PROGRAMADOR',1050.00,3);
INSERT INTO cadfun VALUES (default,'CARLOS BASTOS','5','VENDEDOR',1530.00,2);
INSERT INTO cadfun VALUES (default,'PEDRO SILVA','3','SUPERVISOR',1599.51,1);
INSERT INTO cadfun VALUES (default,'ANA BASTOS','5','VENDEDORA',1530.00,0);
INSERT INTO cadfun VALUES (default,'PAULO DA SILVA','2','VENDEDOR',1530.00,1);

select * FROM cadfun;
-- 7
select SUM(SALARIO + 250) AS SALARIO FROM cadfun where CODFUN = '1';
--8
select NOME , FUNCAO FROM cadfun
where FUNCAO = 'ANALISTA';
--9
select NOME, SALARIO FROM cadfun
WHERE SALARIO > 1700;
--10
select NOME, SALARIO FROM cadfun
WHERE SALARIO < 1700;
--11
select NOME, SALARIO FROM cadfun
WHERE SALARIO = 1700;
--12
select * FROM cadfun
WHERE FUNCAO = 'PROGRAMADOR' OR FUNCAO = 'ANALISTA' ;
--13
select * FROM cadfun
WHERE FUNCAO IN ('PROGRAMADOR','ANALISTA') AND SALARIO > 1200;
--14
SELECT * FROM cadfun
WHERE FUNCAO NOT IN ('PROGRAMADOR', 'ANALISTA');
--15
SELECT * FROM cadfun
WHERE FILHOS BETWEEN 2 AND 4;
--extra
SELECT NOME,FUNCAO, SALARIO * 1.25 FROM cadfun;
--16
SELECT * FROM cadfun
WHERE FILHOS BETWEEN 2 AND 4 and SALARIO < 2000;
--17
SELECT * FROM cadfun
WHERE FILHOS !=2 and FILHOS !=3;
--18
SELECT * FROM cadfun
WHERE FILHOS !=2 and FILHOS !=3 and FILHOS != 0;
--19
SELECT * FROM cadfun
WHERE FILHOS in (2,3);