CREATE DATABASE exemplo1

CREATE DATABASE exemplo2

DROP DATABASE exemplo2

-- COMANDOS PARA CRIAR TABELAS

CREATE TABLE FUNCIONARIOS(
	id_funcionario SERIAL NOT NULL PRIMARY KEY,
	nome_funcionario VARCHAR(100) NOT NULL,
	status_funcionario BOOLEAN NOT NULL,
	cidade_funcionario VARCHAR(100)	
);

CREATE TABLE PRODUTOS(
	id_produto INT NOT NULL PRIMARY KEY,
	nome_produto VARCHAR(255) NOT NULL,
	quantidade_produto INT NOT NULL,
	valor_produto DECIMAL(7,2),
	validade_produto DATE NOT NULL
	FOREIGN KEY id_funcionario REFERENCES FUNCIONARIOS --CHAVE ESTRANGEIRA
);

CREATE TABLE modelo(
	id_modelo INT NOT NULL PRIMARY KEY
);

-- COMANDOS PARA APAGAR TABELA

DROP TABLE modelo

-- COMANDO VISUALIZAR TABELAS

SELECT * FROM FUNCIONARIOS
SELECT * FROM PRODUTOS

-- COMANDOS PARA ALTERAR CAMPOS DE TABELA

ALTER TABLE funcionarios
ADD sexo CHAR(1)

ALTER TABLE funcionarios
DROP COLUMN sexo